export const MOCK_COMPLIANCES = [
    {
        id: '1',
        title: 'GST Return Filing (GSTR-1)',
        description: 'Monthly return for outward supplies',
        dueDate: '2026-11-11', // ISO format
        type: 'GST',
        status: 'Pending',
        isRequired: true,
        businessType: ['Retail', 'Service', 'Manufacturing'],
    },
    {
        id: '2',
        title: 'GST Return Filing (GSTR-3B)',
        description: 'Monthly summary return',
        dueDate: '2026-11-20',
        type: 'GST',
        status: 'Upcoming',
        isRequired: true,
        businessType: ['Retail', 'Service', 'Manufacturing'],
    },
    {
        id: '3',
        title: 'Shop & Establishment License Renewal',
        description: 'Annual renewal of shop license',
        dueDate: '2026-12-31',
        type: 'License',
        status: 'Completed',
        isRequired: true,
        businessType: ['Retail'],
    },
    {
        id: '4',
        title: 'Professional Tax Payment',
        description: 'Monthly professional tax payment',
        dueDate: '2026-11-30',
        type: 'Tax',
        status: 'Pending',
        isRequired: true,
        businessType: ['Service', 'Freelancer'],
    },
    {
        id: '5',
        title: 'Income Tax Advance Tax',
        description: 'Quarterly advance tax payment',
        dueDate: '2026-12-15',
        type: 'Tax',
        status: 'Upcoming',
        isRequired: true,
        businessType: ['Manufacturing', 'Service', 'Retail', 'Freelancer'],
    },
];
